import sqlite3

dbfile = 'constitutions.sqlite'
con = sqlite3.connect(dbfile)

with con:
    cur = con.cursor()
    cur.execute('UPDATE constitutions SET countrycode = "ly" WHERE lower(country) = "libia"')
    cur.execute('UPDATE constitutions SET countrycode = "fm" WHERE lower(country) = "micronesia__fed_states_of_"')
    cur.execute('UPDATE constitutions SET countrycode = "km" WHERE lower(country) = "comoros_the"')
    #cur.execute('UPDATE constitutions SET countrycode = "la" WHERE lower(country) = "lao_people_s_democratic_republic__the"')
    #cur.execute('UPDATE constitutions SET countrycode = "kr" WHERE lower(country) = "republic_of_korea__the"')
    cur.execute('UPDATE constitutions SET countrycode = "us" WHERE lower(country) = "united_states_of_america"')
    cur.execute('UPDATE constitutions SET countrycode = "ci" WHERE lower(country) = "cote_d_ivoire"')
    cur.execute('UPDATE constitutions SET countrycode = "sy" WHERE lower(country) = "syrian_arab_republic_the"')
    cur.execute('UPDATE constitutions SET countrycode = "nl" WHERE lower(country) = "netherlands_the"')
    cur.execute('UPDATE constitutions SET countrycode = "cf" WHERE lower(country) = "central_african_republic_the"')
    #cur.execute('UPDATE constitutions SET countrycode = "cg" WHERE lower(country) = "Congo_the"')
    #cur.execute('UPDATE constitutions SET countrycode = "??" WHERE lower(country) = "Montenegro"')
    cur.execute('UPDATE constitutions SET countrycode = "ae" WHERE lower(country) = "united_arab_emirates__the"')
    cur.execute('UPDATE constitutions SET countrycode = "vn" WHERE lower(country) = "viet_nam"')
    #cur.execute('UPDATE constitutions SET countrycode = "??" WHERE lower(country) = "the_former_yugoslav_republic_of_macedonia"')
    #cur.execute('UPDATE constitutions SET countrycode = "??" WHERE lower(country) = "russian_federation__the"')
    cur.execute('UPDATE constitutions SET countrycode = "ne" WHERE lower(country) = "niger_the"')
    cur.execute('UPDATE constitutions SET countrycode = "cz" WHERE lower(country) = "czech_republic_the"')
    #cur.execute('UPDATE constitutions SET countrycode = "tp" WHERE lower(country) = "timor-leste"')
    cur.execute('UPDATE constitutions SET countrycode = "ir" WHERE lower(country) = "iran_islamic_rep_of_"')
    #cur.execute('UPDATE constitutions SET countrycode = "??" WHERE lower(country) = "Kosovo"')
    cur.execute('UPDATE constitutions SET countrycode = "cd" WHERE lower(country) = "democratic_republic_of_the_congo"')
    cur.execute('UPDATE constitutions SET countrycode = "mh" WHERE lower(country) = "marshall_islands__the"')
    cur.execute('UPDATE constitutions SET countrycode = "ph" WHERE lower(country) = "philippines__the"')
    cur.execute('UPDATE constitutions SET countrycode = "sd" WHERE lower(country) = "sudan_the"')
    #cur.execute('UPDATE constitutions SET countrycode = "??" WHERE lower(country) = "south_sudan"')
    cur.execute('UPDATE constitutions SET countrycode = "do" WHERE lower(country) = "dominican_republic_the"')
    cur.execute('UPDATE constitutions SET countrycode = "tz" WHERE lower(country) = "united_republic_of_tanzania__the"')
    cur.execute('UPDATE constitutions SET countrycode = "bs" WHERE lower(country) = "bahamas_the"')
    cur.execute('UPDATE constitutions SET countrycode = "mm" WHERE lower(country) = "Myanmar"')
    cur.execute('UPDATE constitutions SET countrycode = "gm" WHERE lower(country) = "gambia__the"')
    cur.execute('UPDATE constitutions SET countrycode = "zw" WHERE lower(country) = "zimbabwe"')
con.close()